{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintHaskellScript.
--   Generated by the BNF converter.

module PrintHaskellScript where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsHaskellScript

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsHaskellScript.Ident where
  prt _ (AbsHaskellScript.Ident i) = doc $ showString i
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsHaskellScript.Udent where
  prt _ (AbsHaskellScript.Udent i) = doc $ showString i

instance Print (AbsHaskellScript.Program' a) where
  prt i = \case
    AbsHaskellScript.Program _ stmts -> prPrec i 0 (concatD [prt 0 stmts])

instance Print [AbsHaskellScript.Ident] where
  prt = prtList

instance Print [AbsHaskellScript.Stmt' a] where
  prt = prtList

instance Print (AbsHaskellScript.Block' a) where
  prt i = \case
    AbsHaskellScript.Block _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print (AbsHaskellScript.Stmt' a) where
  prt i = \case
    AbsHaskellScript.Decl _ id_ expr -> prPrec i 0 (concatD [doc (showString "const"), prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsHaskellScript.FunDecl _ id_1 types id_2 expr -> prPrec i 0 (concatD [prt 0 id_1, doc (showString "::"), prt 0 types, doc (showString "const"), prt 0 id_2, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsHaskellScript.DataDecl _ udent typeargs constructors -> prPrec i 0 (concatD [doc (showString "data"), prt 0 udent, doc (showString "("), prt 0 typeargs, doc (showString ")"), doc (showString "="), doc (showString "{"), prt 0 constructors, doc (showString "}"), doc (showString ";")])
    AbsHaskellScript.Cond _ expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsHaskellScript.CondElse _ expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    AbsHaskellScript.Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsHaskellScript.VoidRet _ -> prPrec i 0 (concatD [doc (showString "return;")])
    AbsHaskellScript.Print _ exprs -> prPrec i 0 (concatD [doc (showString "_print"), doc (showString "("), prt 0 exprs, doc (showString ")"), doc (showString ";")])
    AbsHaskellScript.Match _ id_ cases -> prPrec i 0 (concatD [doc (showString "match"), prt 0 id_, doc (showString ":"), prt 0 cases])
    AbsHaskellScript.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsHaskellScript.Case' a) where
  prt i = \case
    AbsHaskellScript.Case _ expr block -> prPrec i 0 (concatD [doc (showString "case"), prt 0 expr, prt 0 block])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsHaskellScript.Case' a] where
  prt = prtList

instance Print (AbsHaskellScript.Type' a) where
  prt i = \case
    AbsHaskellScript.Int _ -> prPrec i 0 (concatD [doc (showString "Int")])
    AbsHaskellScript.Str _ -> prPrec i 0 (concatD [doc (showString "String")])
    AbsHaskellScript.Bool _ -> prPrec i 0 (concatD [doc (showString "Bool")])
    AbsHaskellScript.Void _ -> prPrec i 0 (concatD [doc (showString "Void")])
    AbsHaskellScript.FunT _ types -> prPrec i 0 (concatD [doc (showString "("), prt 0 types, doc (showString ")")])
    AbsHaskellScript.ListT _ type_ -> prPrec i 0 (concatD [doc (showString "["), prt 0 type_, doc (showString "]")])
    AbsHaskellScript.WildcardT _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsHaskellScript.DataType _ udent typeargs -> prPrec i 0 (concatD [prt 0 udent, doc (showString "("), prt 0 typeargs, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString "->"), prt 0 xs]

instance Print [AbsHaskellScript.Type' a] where
  prt = prtList

instance Print (AbsHaskellScript.TypeArg' a) where
  prt i = \case
    AbsHaskellScript.TypeArg _ type_ -> prPrec i 0 (concatD [prt 0 type_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsHaskellScript.TypeArg' a] where
  prt = prtList

instance Print (AbsHaskellScript.Constructor' a) where
  prt i = \case
    AbsHaskellScript.Constructor _ udent typeargs -> prPrec i 0 (concatD [prt 0 udent, doc (showString "("), prt 0 typeargs, doc (showString ")")])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString "|"), prt 0 xs]

instance Print [AbsHaskellScript.Constructor' a] where
  prt = prtList

instance Print (AbsHaskellScript.Expr' a) where
  prt i = \case
    AbsHaskellScript.EVar _ id_ -> prPrec i 8 (concatD [prt 0 id_])
    AbsHaskellScript.EConstr _ udent -> prPrec i 8 (concatD [prt 0 udent])
    AbsHaskellScript.ELitInt _ n -> prPrec i 8 (concatD [prt 0 n])
    AbsHaskellScript.EString _ str -> prPrec i 8 (concatD [prt 0 str])
    AbsHaskellScript.ELitTrue _ -> prPrec i 8 (concatD [doc (showString "true")])
    AbsHaskellScript.ELitFalse _ -> prPrec i 8 (concatD [doc (showString "false")])
    AbsHaskellScript.Ternary _ expr1 expr2 expr3 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "?"), prt 1 expr2, doc (showString ":"), prt 1 expr3])
    AbsHaskellScript.LongLambda _ ids block -> prPrec i 7 (concatD [doc (showString "\\"), prt 0 ids, doc (showString "=>"), prt 0 block])
    AbsHaskellScript.ConciseLambda _ ids expr -> prPrec i 7 (concatD [doc (showString "\\"), prt 0 ids, doc (showString "=>"), prt 8 expr])
    AbsHaskellScript.Spread _ expr -> prPrec i 0 (concatD [doc (showString "..."), prt 1 expr])
    AbsHaskellScript.ListExpr _ exprs -> prPrec i 7 (concatD [doc (showString "["), prt 0 exprs, doc (showString "]")])
    AbsHaskellScript.EApp _ expr exprs -> prPrec i 6 (concatD [prt 7 expr, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsHaskellScript.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsHaskellScript.Not _ expr -> prPrec i 5 (concatD [doc (showString "not"), prt 6 expr])
    AbsHaskellScript.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsHaskellScript.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsHaskellScript.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsHaskellScript.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "and"), prt 1 expr2])
    AbsHaskellScript.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "or"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsHaskellScript.Expr' a] where
  prt = prtList

instance Print (AbsHaskellScript.AddOp' a) where
  prt i = \case
    AbsHaskellScript.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    AbsHaskellScript.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (AbsHaskellScript.MulOp' a) where
  prt i = \case
    AbsHaskellScript.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    AbsHaskellScript.Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    AbsHaskellScript.Mod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (AbsHaskellScript.RelOp' a) where
  prt i = \case
    AbsHaskellScript.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    AbsHaskellScript.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsHaskellScript.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    AbsHaskellScript.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsHaskellScript.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    AbsHaskellScript.NE _ -> prPrec i 0 (concatD [doc (showString "!=")])

